name: FE CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [control, operation]

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          # 보여질 커밋 히스토리 수를 설정 
          fetch-depth: 2  

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          # 노드 버전 설정
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
        working-directory: apps/${{ matrix.service }}
      
      - name: Build ${{ matrix.service }}
        run: pnpm run build
        working-directory: apps/${{ matrix.service }}

      - name: Test ${{ matrix.service }}
        run: pnpm test
        working-directory: apps/${{ matrix.service }}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.service }}-build
          path: apps/${{ matrix.service }}/dist

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    strategy:
      matrix:
        service: [control, operation]
    uses: ./.github/workflows/cd.yml
    with:
      service: ${{ matrix.service }}
    secrets: inherit